#!/bin/bash

set -e

# generate a password for root.
ROOT_PASSWORD=$(pwgen -c -n -1 12)
echo "root:$ROOT_PASSWORD" | chpasswd
echo User: root Password: $ROOT_PASSWORD

# start supervisord
/usr/bin/supervisord

echo "Starting openssh server..."
supervisorctl start sshd >/dev/null

appStart () {
	chown -R mongodb:mongodb /var/lib/mongodb

	echo "Starting mongodb server..."
	supervisorctl start mongodb >/dev/null

	tail -F /var/log/mongodb/mongodb.log
}

appHelp () {
	echo "Available options:"
	echo " app:start          - Start mongodb server and watch the logs (default)"
	echo " app:help           - Displays the help"
	echo " [command]          - Execute the specified linux command eg. bash."
}

case "$1" in
	app:start)
		appStart
		;;
	app:help)
		appHelp
		;;
	*)
		if [ -x $1 ]; then
			$1
		else
			prog=$(which $1)
			if [ -n "${prog}" ] ; then
				shift 1
				$prog $@
			else
				appHelp
			fi
		fi
		;;
esac

exit 0
